# Generated by Django 3.1.3 on 2020-11-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('brand_name_korean', models.CharField(max_length=45)),
                ('brand_name_english', models.CharField(max_length=45)),
                ('brand_crm_number', models.CharField(max_length=45)),
                ('is_master', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=200, null=True)),
                ('background_image', models.CharField(max_length=200, null=True)),
                ('simple_introduce', models.CharField(max_length=45, null=True)),
                ('detail_introduce', models.CharField(max_length=45, null=True)),
                ('brand_crm_open', models.CharField(max_length=15, null=True)),
                ('brand_crm_end', models.CharField(max_length=15, null=True)),
                ('is_brand_crm_holiday', models.BooleanField(default=False)),
                ('zip_code', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=45, null=True)),
                ('detail_address', models.CharField(max_length=45, null=True)),
                ('delivery_information', models.CharField(max_length=45, null=True)),
                ('refund_exchange_information', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='SellerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'seller_properties',
            },
        ),
        migrations.CreateModel(
            name='SellerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='입점대기', max_length=45)),
            ],
            options={
                'db_table': 'seller_status',
            },
        ),
        migrations.CreateModel(
            name='SellerStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('seller_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerstatus')),
            ],
            options={
                'db_table': 'seller_status_histories',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerproperty'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerstatus'),
        ),
        migrations.CreateModel(
            name='ManagerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('ordering', models.IntegerField(null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'db_table': 'manager_information',
            },
        ),
    ]
